name = "MeshCatBenchmarkMechanisms"
uuid = "e83dc370-f0ba-44d1-a240-217e19b8d23b"
authors = ["Juraj Lieskovsk√Ω <lieskovsky.juraj@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"

[compat]
Colors = "0.13.0"
CoordinateTransformations = "0.6.3"
GeometryBasics = "0.4.11"
MeshCat = "1.0.0"
Reexport = "1.2.2"
Rotations = "1.7.1"
